/* Gì cũng được!!! — service worker: chơi offline, tự cập nhật ở lần mở sau */
const CACHE='gcd-v'+'1.5.6';
const CORE=['./','./index.html','./manifest.webmanifest','./icon-192.png','./icon-512.png','./apple-touch-icon.png','./art/bg_date_cafe.webp','./art/bg_date_cinema_tam.webp','./art/bg_date_food.webp','./art/bg_date_park.webp','./art/bg_date_stall.webp','./art/bg_pickup_day.webp','./art/bg_pickup_night.webp','./art/bg_roadside_night.webp','./art/bg_room_minh_evening.webp','./art/bg_room_minh_morning.webp','./art/bg_room_minh_noon.webp','./art/bg_street_day.webp','./art/bg_street_night.webp','./art/cg_lan_pho.webp','./art/lan_day_angry.webp','./art/lan_day_blink.webp','./art/lan_day_crossed.webp','./art/lan_day_happy.webp','./art/lan_day_laugh.webp','./art/lan_day_love.webp','./art/lan_day_neutral.webp','./art/lan_day_sad.webp','./art/lan_day_sit.webp','./art/lan_day_stand.webp','./art/lan_day_talk.webp','./art/lan_day_wave.webp','./art/lan_night_angry.webp','./art/lan_night_blink.webp','./art/lan_night_crossed.webp','./art/lan_night_happy.webp','./art/lan_night_love.webp','./art/lan_night_neutral.webp','./art/lan_night_sad.webp','./art/lan_night_sit.webp','./art/lan_night_stand.webp','./art/lan_night_talk.webp','./art/lan_night_wave.webp','./art/lan_rain.webp','./art/lan_var_earring.webp','./art/lan_var_glasses.webp','./art/lan_var_lipstick.webp','./art/lan_var_ponytail.webp','./art/lan_var_ribbon.webp','./art/lan_wedding.webp','./art/minh_bust_happy.webp','./art/minh_bust_neutral.webp','./art/minh_bust_worried.webp','./art/minh_day_crossed.webp','./art/minh_day_drive.webp','./art/minh_day_sit.webp','./art/minh_day_stand.webp','./art/minh_night_crossed.webp','./art/minh_night_drive.webp','./art/minh_night_sit.webp','./art/minh_night_stand.webp','./art/minh_rain_drive.webp','./art/minh_wed_stand.webp','./art/ride_lanminh_day.webp','./art/ride_lanminh_night.webp','./art/ride_lanminh_rain.webp','./art/veh_oto_side.webp','./art/veh_tayga_front.webp','./art/veh_tayga_side.webp','./art/veh_vespa_front.webp','./art/veh_vespa_side.webp','./art/veh_xeso_front.webp','./art/veh_xeso_side.webp'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',e=>{
  if(e.request.method!=='GET')return;
  const u=new URL(e.request.url);if(u.origin!==location.origin)return;
  e.respondWith(caches.match(e.request,{ignoreSearch:true}).then(hit=>{
    const net=fetch(e.request).then(r=>{if(r&&r.ok){const cp=r.clone();caches.open(CACHE).then(c=>c.put(e.request,cp))}return r}).catch(()=>hit);
    return hit||net;
  }));
});
